# Generated by Django 3.2.5 on 2021-07-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(default='book', max_length=200)),
                ('author', models.CharField(default='author', max_length=200)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Telugu', 'Telugu'), ('Malyalam', 'Malyalam'), ('French', 'French')], default='english', max_length=200)),
                ('genre', models.CharField(choices=[('NonFiction', 'Nonfiction'), ('Fiction', 'Fiction'), ('Satire', 'Satire'), ('Classic', 'Classic'), ('Adventure', 'Adventure')], default='english', max_length=200)),
            ],
        ),
    ]
