# Generated by Django 3.2.5 on 2021-07-09 14:12

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(default='book', max_length=200)),
                ('author', models.CharField(default='author', max_length=200)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Telugu', 'Telugu'), ('Malyalam', 'Malyalam'), ('French', 'French')], default='English', max_length=200)),
                ('genre', models.CharField(choices=[('NonFiction', 'Nonfiction'), ('Fiction', 'Fiction'), ('Satire', 'Satire'), ('Classic', 'Classic'), ('Adventure', 'Adventure')], default='Fiction', max_length=200)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
