# Generated by Django 3.2.5 on 2021-07-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='genre',
            field=models.CharField(choices=[('NonFiction', 'Nonfiction'), ('Fiction', 'Fiction'), ('Satire', 'Satire'), ('Classic', 'Classic'), ('Adventure', 'Adventure')], default='Fiction', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Telugu', 'Telugu'), ('Malyalam', 'Malyalam'), ('French', 'French')], default='English', max_length=200),
        ),
    ]
