# Generated by Django 3.2.5 on 2021-07-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='booktags',
            field=models.CharField(default='tag1', max_length=200),
        ),
    ]
